const STAR_FX_MS=1600;
const sounds=[
 {id:'b',name:'b',tip:'嘴唇合起來，輕輕說 b。',word:'波波球',sentence:'波波拿波波球。',syllables:[['bō','b'],['bō','b'],['qiú','q']]},
 {id:'p',name:'p',tip:'說 p 時，感覺有一點風。',word:'山坡',sentence:'小明走上山坡。',syllables:[['shān','sh'],['pō','p']]},
 {id:'m',name:'m',tip:'合起嘴唇，哼 mmm。',word:'米飯',sentence:'媽媽煮米飯。',syllables:[['mǐ','m'],['fàn','f']]},
 {id:'f',name:'f',tip:'牙齒輕輕碰下唇，吹 fff。',word:'風車',sentence:'風車不停轉動。',syllables:[['fēng','f'],['chē','ch']]}
];
const questions=[...['b','p','m','f','b'].map(answer=>({type:'listen',answer,prompt:'聽一聽，這是哪個聲母？',context:sounds.find(s=>s.id===answer),hint:`提示：${sounds.find(s=>s.id===answer).tip}`,audio:`assets/pth/initials/audio/${answer}.m4a`})),...['p','m','f','b','p'].map(answer=>({type:'shape',answer,prompt:'看口形，找出對應聲母。',context:sounds.find(s=>s.id===answer),hint:`提示：${sounds.find(s=>s.id===answer).tip}`,video:`assets/pth/initials/video/${answer}.mp4`}))];
const $=s=>document.querySelector(s);const sharedAudio=$('#sharedAudio');let audioTimer=null;function playAudio(src){if(audioTimer)clearTimeout(audioTimer);sharedAudio.pause();sharedAudio.currentTime=0;sharedAudio.src=src;sharedAudio.classList.add('playing');sharedAudio.play().catch(()=>{});audioTimer=setTimeout(()=>sharedAudio.classList.remove('playing'),Math.max(800,(sharedAudio.duration||1)*1000));}function stopAudio(){sharedAudio.pause();sharedAudio.currentTime=0;sharedAudio.classList.remove('playing');}const key='kaka-pth-v1';let state=JSON.parse(localStorage.getItem(key)||'null')||{roundIndex:0,roundStars:0,totalStars:0,completed:false};let qi=state.roundIndex||0,selected=null;const save=()=>localStorage.setItem(key,JSON.stringify(state));
function renderStars(){const n=state.roundStars||0;const html=Array.from({length:10},(_,i)=>`<span class="${i<n?'on':''}">${i<n?'★':'☆'}</span>`).join('');const track=Array.from({length:10},(_,i)=>`<span class="star ${i<n?'on':''}">${i<n?'★':'☆'}</span>`).join('');$('#miniStars').innerHTML=html;$('#starTrack').innerHTML=track;$('#starsTotal').textContent=`${n}/10 ⭐（累積完成 ${Math.floor((state.totalStars||0)/10)} 輪・${state.totalStars||0} 星）`;$('#progressBadge').textContent=`${n}/10 ⭐`;$('#quizTabCount').textContent=`${n}/10`;$('#completeMessage').hidden=n<10;}
function renderLearn(){$('#lessonGrid').innerHTML=sounds.map(s=>`<article class="lesson"><h3>${s.name}</h3><p>${s.tip}</p><div class="example"><strong>${s.word}</strong><span>${s.syllables.map(x=>x[0]).join(' ')}</span><small>${s.sentence}</small></div><video controls playsinline preload="metadata" src="assets/pth/initials/video/${s.id}.mp4"></video><button class="audio-btn" data-audio="assets/pth/initials/audio/${s.id}.m4a">🔊 聽一聽</button></article>`).join('');document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>playAudio(b.dataset.audio));}
function showTab(id){stopAudio();if(id==='quiz'&&state.completed){id='stars';}document.querySelectorAll('.panel').forEach(p=>{p.hidden=p.id!==id;p.classList.toggle('active',p.id===id)});document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));if(id==='quiz')renderQuestion();}
function revealContext(s){const spans=s.syllables.map(([text,initial])=>`<span class="syllable ${initial===s.id?'target':''}">${text}</span>`).join(' ');return `<div class="context-card revealed"><strong>${s.word}</strong><span class="pinyin">${spans}</span><small>${s.sentence}</small></div>`;}
function renderQuestion(){const q=questions[qi];$('#questionNo').textContent=qi+1;$('#questionPrompt').textContent=q.prompt;$('#feedback').textContent='';$('#feedback').className='feedback';selected=null;$('#submitAnswer').disabled=true;$('#quizMedia').innerHTML=q.type==='listen'?`<div class="blind-context">🔊<small>先聽聲音，再選聲母</small></div>`:`<div class="blind-context"><video controls autoplay muted playsinline src="${q.video}"></video><small>先看口形，再選聲母</small></div>`;$('#quizMedia').onclick=()=>q.type==='listen'&&playAudio(q.audio);const shuffled=[...sounds].sort(()=>Math.random()-.5);$('#options').innerHTML=shuffled.map(s=>`<button class="option" data-answer="${s.id}">${s.name}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.answer;$('#submitAnswer').disabled=false;});}
function fireStar(){const index=Math.max(1,state.roundStars);document.querySelector('#miniStars span:nth-child('+index+')')?.classList.add('target-glow');document.querySelector('#starTrack span:nth-child('+index+')')?.classList.add('target-glow');const fx=document.createElement('div');fx.className='star-fx';fx.innerHTML='<img src="assets/kaka-ranger-solo.png" alt="KAKA Ranger"><i>✦</i><span>★</span>';$('#quizMedia').append(fx);setTimeout(()=>fx.remove(),STAR_FX_MS);}
$('#startQuiz').onclick=()=>{if(state.completed){showTab('stars');return;}showTab('quiz');};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showTab(t.dataset.tab));$('#submitAnswer').onclick=()=>{if($('#submitAnswer').disabled)return;const q=questions[qi];if(selected!==q.answer){$('#feedback').textContent=q.hint;return;}stopAudio();state.roundStars=Math.min(10,state.roundStars+1);state.roundIndex=qi+1;$('#submitAnswer').disabled=true;save();$('#quizMedia').insertAdjacentHTML('afterbegin',revealContext(q.context));renderStars();fireStar();$('#feedback').textContent='答對了！看清楚聲母在拼音的哪個位置。';$('#feedback').className='feedback good';setTimeout(()=>{if(state.roundStars>=10){state.totalStars+=10;state.completed=true;state.roundIndex=0;save();showTab('stars');}else{qi=(qi+1)%questions.length;renderQuestion();}},STAR_FX_MS+100);};$('#resetProgress').onclick=()=>{state={roundIndex:0,roundStars:0,totalStars:state.totalStars||0,completed:false};qi=0;save();renderStars();showTab('learn');};renderLearn();renderStars();
