const sounds=[
 {id:'b',name:'b',tip:'雙唇先合起來，送氣較少。',word:'波波球',sentence:'波波拿波波球。',pinyin:'bō bō qiú'},
 {id:'p',name:'p',tip:'雙唇先合起來，送氣較多。',word:'山坡',sentence:'小明走上山坡。',pinyin:'shān pō'},
 {id:'m',name:'m',tip:'雙唇合起來，鼻音響亮。',word:'米飯',sentence:'媽媽煮米飯。',pinyin:'mā ma zhǔ mǐ fàn'},
 {id:'f',name:'f',tip:'上齒輕碰下唇，摩擦出聲。',word:'風車',sentence:'風車不停轉動。',pinyin:'fēng chē'}
];
const questions=[...['b','p','m','f','b'].map(answer=>({type:'listen',answer,prompt:`聽一聽：「${sounds.find(s=>s.id===answer).word}」的開頭聲母是甚麼？`,context:sounds.find(s=>s.id===answer),hint:`提示：${sounds.find(s=>s.id===answer).tip}`,audio:`assets/pth/initials/audio/${answer}.m4a`})),...['p','m','f','b','p'].map(answer=>({type:'shape',answer,prompt:`看口形，找出「${sounds.find(s=>s.id===answer).word}」的開頭聲母。`,context:sounds.find(s=>s.id===answer),hint:`提示：${sounds.find(s=>s.id===answer).tip}`,video:`assets/pth/initials/video/${answer}.mp4`}))];
const key='kaka-pth-v1';let state=JSON.parse(localStorage.getItem(key)||'null')||{stars:0};let qi=0,selected=null;const $=s=>document.querySelector(s);const save=()=>localStorage.setItem(key,JSON.stringify({stars:state.stars}));
function renderStars(){const html=Array.from({length:10},(_,i)=>`<span class="${i<state.stars?'on':''}">${i<state.stars?'★':'☆'}</span>`).join('');$('#miniStars').innerHTML=html;$('#starTrack').innerHTML=html.replaceAll('<span','<span class="star');$('#starsTotal').textContent=`${state.stars}/10 ⭐`;$('#progressBadge').textContent=`${state.stars}/10 ⭐`;$('#quizTabCount').textContent=`${state.stars}/10`;$('#completeMessage').hidden=state.stars<10;}
function renderLearn(){$('#lessonGrid').innerHTML=sounds.map(s=>`<article class="lesson"><h3>${s.name}</h3><p>${s.tip}</p><div class="example"><strong>${s.word}</strong><span>${s.pinyin}</span><small>${s.sentence}</small></div><video controls playsinline preload="metadata" src="assets/pth/initials/video/${s.id}.mp4"></video><button class="audio-btn" data-audio="assets/pth/initials/audio/${s.id}.m4a">🔊 聽一聽</button></article>`).join('');document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>new Audio(b.dataset.audio).play());}
function showTab(id){document.querySelectorAll('.panel').forEach(p=>{p.hidden=p.id!==id;p.classList.toggle('active',p.id===id)});document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));if(id==='quiz')renderQuestion();}
function renderQuestion(){const q=questions[qi];$('#questionNo').textContent=qi+1;$('#questionPrompt').textContent=q.prompt;$('#feedback').textContent='';$('#feedback').className='feedback';selected=null;$('#submitAnswer').disabled=true;const marked=q.context.pinyin.replace(new RegExp(`^${q.answer}`,'i'),`<mark>${q.answer}</mark>`);$('#quizMedia').innerHTML=`<div class="context-card"><strong>${q.context.word}</strong><span class="pinyin">${marked}</span><small>${q.context.sentence}</small></div>`+(q.type==='listen'?`<button class="sound-btn" aria-label="播放聲音">🔊</button><small>撳一下聽聲音</small>`:`<video controls autoplay muted playsinline src="${q.video}"></video>`);$('#quizMedia').onclick=()=>q.type==='listen'&&new Audio(q.audio).play();$('#options').innerHTML=sounds.map(s=>`<button class="option" data-answer="${s.id}">${s.name}<small>${s.word}</small></button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.answer;$('#submitAnswer').disabled=false;});}
$('#startQuiz').onclick=()=>showTab('quiz');document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showTab(t.dataset.tab));$('#submitAnswer').onclick=()=>{const q=questions[qi];if(selected!==q.answer){$('#feedback').textContent=q.hint;return;}state.stars=Math.min(10,state.stars+1);save();renderStars();$('#feedback').textContent='答對了！KAKA Ranger 射出一粒星 ⭐';$('#feedback').className='feedback good';setTimeout(()=>{if(state.stars>=10)showTab('stars');else{qi=(qi+1)%questions.length;renderQuestion();}},700);};$('#resetProgress').onclick=()=>{state.stars=0;qi=0;save();renderStars();showTab('learn');};renderLearn();renderStars();
