/** 卡卡學習 — 字詞表（繁體表面形）
 *  插圖採用系統 Emoji（iPhone／iPad 會顯示 Apple Color Emoji，清晰易認）
 */

const DEER_IDS = ['lu', 'meihualu', 'xunlu', 'tuolu', 'malu'];

/**
 * badge：少數鹿種共用 🦌 時嘅細標記，幫 KAKA 分辨
 * plate：卡片底色，加強視覺區分
 */
const WORDS = [
  { id: 'lu', term: '鹿', isDeer: true, emoji: '🦌', badge: '', plate: '#1a4d3a' },
  { id: 'meihualu', term: '梅花鹿', isDeer: true, emoji: '🦌', badge: '🌸', plate: '#4a3b1a' },
  { id: 'xunlu', term: '馴鹿', isDeer: true, emoji: '🦌', badge: '❄️', plate: '#1a2a4a' },
  { id: 'tuolu', term: '駝鹿', isDeer: true, emoji: '🫎', badge: '', plate: '#4a2a12' },
  { id: 'malu', term: '馬鹿', isDeer: true, emoji: '🦌', badge: '馬', plate: '#2a4018' },
  { id: 'gou', term: '狗', isDeer: false, emoji: '🐶', badge: '', plate: '#3a3010', en: { word: 'dog', letters: ['d', 'o', 'g'] } },
  { id: 'mao', term: '貓', isDeer: false, emoji: '🐱', badge: '', plate: '#4a2030', en: { word: 'cat', letters: ['c', 'a', 't'] } },
  { id: 'yu', term: '魚', isDeer: false, emoji: '🐟', badge: '', plate: '#0f3550' },
  { id: 'niao', term: '鳥', isDeer: false, emoji: '🐦', badge: '', plate: '#1a3050' },
  { id: 'tu', term: '兔子', isDeer: false, emoji: '🐰', badge: '', plate: '#402038' },
  { id: 'yang', term: '羊', isDeer: false, emoji: '🐑', badge: '', plate: '#2a2a35' },
  { id: 'niu', term: '牛', isDeer: false, emoji: '🐮', badge: '', plate: '#3a3010' },
  { id: 'ma', term: '馬', isDeer: false, emoji: '🐴', badge: '', plate: '#2a2520' },
  { id: 'zhu', term: '豬', isDeer: false, emoji: '🐷', badge: '', plate: '#402030', en: { word: 'pig', letters: ['p', 'i', 'g'] } },
  { id: 'xiong', term: '熊', isDeer: false, emoji: '🐻', badge: '', plate: '#3a2810' },
  { id: 'shizi', term: '獅子', isDeer: false, emoji: '🦁', badge: '', plate: '#3a3010' },
  { id: 'laohu', term: '老虎', isDeer: false, emoji: '🐯', badge: '', plate: '#402010' },
  { id: 'daxiang', term: '大象', isDeer: false, emoji: '🐘', badge: '', plate: '#243040' },
  { id: 'hou', term: '猴子', isDeer: false, emoji: '🐵', badge: '', plate: '#3a2410' },
  { id: 'xiongmao', term: '熊貓', isDeer: false, emoji: '🐼', badge: '', plate: '#2a2a35' },
  { id: 'changjinglu', term: '長頸鹿', isDeer: false, emoji: '🦒', badge: '', plate: '#3a3010' },
  { id: 'banma', term: '斑馬', isDeer: false, emoji: '🦓', badge: '', plate: '#2a2a35' },
  { id: 'qie', term: '企鵝', isDeer: false, emoji: '🐧', badge: '', plate: '#1a3050' },
  { id: 'hema', term: '河馬', isDeer: false, emoji: '🦛', badge: '', plate: '#2a3548' },
  { id: 'xiniu', term: '犀牛', isDeer: false, emoji: '🦏', badge: '', plate: '#3a3a45' },
  { id: 'luotuo', term: '駱駝', isDeer: false, emoji: '🐪', badge: '', plate: '#3a3010' },
  { id: 'daishu', term: '袋鼠', isDeer: false, emoji: '🦘', badge: '', plate: '#402010' },
  { id: 'shuxiong', term: '樹熊', isDeer: false, emoji: '🐨', badge: '', plate: '#2a2a35' },
  { id: 'huli', term: '狐狸', isDeer: false, emoji: '🦊', badge: '', plate: '#402410' },
  { id: 'eyu', term: '鱷魚', isDeer: false, emoji: '🐊', badge: '', plate: '#143820' },
  { id: 'she', term: '蛇', isDeer: false, emoji: '🐍', badge: '', plate: '#1a4d3a' },
  { id: 'maotouying', term: '貓頭鷹', isDeer: false, emoji: '🦉', badge: '', plate: '#3a2818' },
  { id: 'lang', term: '狼', isDeer: false, emoji: '🐺', badge: '', plate: '#2a2a35' },
  { id: 'haitun', term: '海豚', isDeer: false, emoji: '🐬', badge: '', plate: '#0f3550' },
  { id: 'haibao', term: '海豹', isDeer: false, emoji: '🦭', badge: '', plate: '#1a3050' },
  { id: 'kongque', term: '孔雀', isDeer: false, emoji: '🦚', badge: '', plate: '#143828' },
  { id: 'honghe', term: '紅鶴', isDeer: false, emoji: '🦩', badge: '', plate: '#401028' },
  { id: 'ji', term: '雞', isDeer: false, emoji: '🐔', badge: '', plate: '#402020' },
  { id: 'ya', term: '鴨', isDeer: false, emoji: '🦆', badge: '', plate: '#143828' },
  { id: 'wa', term: '青蛙', isDeer: false, emoji: '🐸', badge: '', plate: '#143820' },
  { id: 'chong', term: '昆蟲', isDeer: false, emoji: '🐛', badge: '', plate: '#2a3810' },
  { id: 'long', term: '龍', isDeer: false, emoji: '🐲', badge: '', plate: '#0f3535' },
  { id: 'bianfu', term: '蝙蝠', isDeer: false, emoji: '🦇', badge: '', plate: '#1a1a22', en: { word: 'bat', letters: ['b', 'a', 't'] } },
  { id: 'ciwei', term: '刺蝟', isDeer: false, emoji: '🦔', badge: '', plate: '#3a2818' },
  // 水果
  { id: 'pingguo', term: '蘋果', isDeer: false, emoji: '🍎', badge: '', plate: '#401820' },
  { id: 'xiangjiao', term: '香蕉', isDeer: false, emoji: '🍌', badge: '', plate: '#3a3410' },
  { id: 'cheng', term: '橙子', isDeer: false, emoji: '🍊', badge: '', plate: '#402410' },
  { id: 'putao', term: '葡萄', isDeer: false, emoji: '🍇', badge: '', plate: '#2a1840' },
  { id: 'xigua', term: '西瓜', isDeer: false, emoji: '🍉', badge: '', plate: '#143820' },
  { id: 'caomei', term: '草莓', isDeer: false, emoji: '🍓', badge: '', plate: '#401028' },
  { id: 'mangguo', term: '芒果', isDeer: false, emoji: '🥭', badge: '', plate: '#402410' },
  { id: 'boluo', term: '菠蘿', isDeer: false, emoji: '🍍', badge: '', plate: '#3a3410' },
  { id: 'tao', term: '桃', isDeer: false, emoji: '🍑', badge: '', plate: '#402038' },
  { id: 'ningmeng', term: '檸檬', isDeer: false, emoji: '🍋', badge: '', plate: '#3a3410' },
  { id: 'yingtao', term: '櫻桃', isDeer: false, emoji: '🍒', badge: '', plate: '#401018' },
  { id: 'qiyiguo', term: '奇異果', isDeer: false, emoji: '🥝', badge: '', plate: '#143820' },
  // 蔬菜
  { id: 'fanqie', term: '番茄', isDeer: false, emoji: '🍅', badge: '', plate: '#401018' },
  { id: 'hongluobo', term: '紅蘿蔔', isDeer: false, emoji: '🥕', badge: '', plate: '#402010' },
  { id: 'yumi', term: '玉米', isDeer: false, emoji: '🌽', badge: '', plate: '#3a3010' },
  { id: 'baicai', term: '白菜', isDeer: false, emoji: '🥬', badge: '', plate: '#143820' },
  { id: 'qiezi', term: '茄子', isDeer: false, emoji: '🍆', badge: '', plate: '#281840' },
  { id: 'qingjiao', term: '青椒', isDeer: false, emoji: '🫑', badge: '', plate: '#143818' },
  { id: 'shuzai', term: '薯仔', isDeer: false, emoji: '🥔', badge: '', plate: '#3a2818' },
  { id: 'yangcong', term: '洋蔥', isDeer: false, emoji: '🧅', badge: '', plate: '#402038' },
  { id: 'mogu', term: '蘑菇', isDeer: false, emoji: '🍄', badge: '', plate: '#401820' },
  { id: 'huanggua', term: '黃瓜', isDeer: false, emoji: '🥒', badge: '', plate: '#143820' },
  { id: 'wandou', term: '豌豆', isDeer: false, emoji: '🫛', badge: '', plate: '#143818' },
  { id: 'nangua', term: '南瓜', isDeer: false, emoji: '🎃', badge: '', plate: '#402010' },
  // 數字 1–10
  { id: 'yi', term: '一', isDeer: false, emoji: '1️⃣', badge: '', plate: '#1a3050' },
  { id: 'er', term: '二', isDeer: false, emoji: '2️⃣', badge: '', plate: '#1a3050' },
  { id: 'san', term: '三', isDeer: false, emoji: '3️⃣', badge: '', plate: '#1a3050' },
  { id: 'si', term: '四', isDeer: false, emoji: '4️⃣', badge: '', plate: '#1a3050' },
  { id: 'wu', term: '五', isDeer: false, emoji: '5️⃣', badge: '', plate: '#1a3050' },
  { id: 'liu', term: '六', isDeer: false, emoji: '6️⃣', badge: '', plate: '#1a3050' },
  { id: 'qi', term: '七', isDeer: false, emoji: '7️⃣', badge: '', plate: '#1a3050' },
  { id: 'ba', term: '八', isDeer: false, emoji: '8️⃣', badge: '', plate: '#1a3050' },
  { id: 'jiu', term: '九', isDeer: false, emoji: '9️⃣', badge: '', plate: '#1a3050' },
  { id: 'shi', term: '十', isDeer: false, emoji: '🔟', badge: '', plate: '#1a3050' },
  // 顏色（橙色 同 水果「橙」分開，避免混淆）
  { id: 'hong', term: '紅色', isDeer: false, emoji: '🔴', badge: '', plate: '#401018' },
  { id: 'huang', term: '黃色', isDeer: false, emoji: '🟡', badge: '', plate: '#3a3410' },
  { id: 'lan', term: '藍色', isDeer: false, emoji: '🔵', badge: '', plate: '#102848' },
  { id: 'lv', term: '綠色', isDeer: false, emoji: '🟢', badge: '', plate: '#143820' },
  { id: 'bai', term: '白色', isDeer: false, emoji: '⚪', badge: '', plate: '#3a3a45' },
  { id: 'hei', term: '黑色', isDeer: false, emoji: '⚫', badge: '', plate: '#1a1a22' },
  { id: 'zi', term: '紫色', isDeer: false, emoji: '🟣', badge: '', plate: '#2a1840' },
  { id: 'fenhong', term: '粉紅', isDeer: false, emoji: '🩷', badge: '', plate: '#402038' },
  { id: 'chengse', term: '橙色', isDeer: false, emoji: '🟠', badge: '', plate: '#402410' },
  { id: 'kafeise', term: '咖啡色', isDeer: false, emoji: '🟤', badge: '', plate: '#3a2818' },
  // 天氣
  { id: 'ri', term: '太陽', isDeer: false, emoji: '☀️', badge: '', plate: '#3a3010' },
  { id: 'yue', term: '月亮', isDeer: false, emoji: '🌙', badge: '', plate: '#1a2040' },
  { id: 'yun', term: '雲朵', isDeer: false, emoji: '☁️', badge: '', plate: '#2a3548' },
  { id: 'yu_rain', term: '下雨', isDeer: false, emoji: '🌧️', badge: '', plate: '#102848' },
  { id: 'xue', term: '雪花', isDeer: false, emoji: '❄️', badge: '', plate: '#2a3a50' },
  { id: 'feng', term: '大風', isDeer: false, emoji: '💨', badge: '', plate: '#243848' },
  { id: 'dian', term: '閃電', isDeer: false, emoji: '⚡', badge: '', plate: '#3a3410' },
  { id: 'caihong', term: '彩虹', isDeer: false, emoji: '🌈', badge: '', plate: '#2a1840' },
  // 自然（單字為主）
  { id: 'xingxing', term: '星星', isDeer: false, emoji: '⭐', badge: '', plate: '#1a2040' },
  { id: 'tiankong', term: '天空', isDeer: false, emoji: '🌤️', badge: '', plate: '#102848' },
  { id: 'hua', term: '花', isDeer: false, emoji: '🌸', badge: '', plate: '#402038' },
  { id: 'cao', term: '草', isDeer: false, emoji: '🌱', badge: '', plate: '#143820' },
  { id: 'shu_tree', term: '樹', isDeer: false, emoji: '🌳', badge: '', plate: '#1a4d3a' },
  { id: 'hai', term: '海', isDeer: false, emoji: '🌊', badge: '', plate: '#0f3550' },
  { id: 'sha', term: '沙', isDeer: false, emoji: '🏜️', badge: '', plate: '#3a3410' },
  { id: 'huo', term: '火', isDeer: false, emoji: '🔥', badge: '', plate: '#401018' },
  { id: 'ye', term: '葉', isDeer: false, emoji: '🍃', badge: '', plate: '#143828' },
  // 交通
  { id: 'che', term: '汽車', isDeer: false, emoji: '🚗', badge: '', plate: '#102848' },
  { id: 'bashi', term: '巴士', isDeer: false, emoji: '🚌', badge: '', plate: '#3a3010' },
  { id: 'huoche', term: '火車', isDeer: false, emoji: '🚂', badge: '', plate: '#401820' },
  { id: 'feiji', term: '飛機', isDeer: false, emoji: '✈️', badge: '', plate: '#1a3050' },
  { id: 'chuan', term: '輪船', isDeer: false, emoji: '🚢', badge: '', plate: '#0f3550' },
  { id: 'danche', term: '單車', isDeer: false, emoji: '🚲', badge: '', plate: '#143828' },
  { id: 'dishi', term: '的士', isDeer: false, emoji: '🚕', badge: '', plate: '#3a3410' },
  { id: 'dianche', term: '電車', isDeer: false, emoji: '🚊', badge: '', plate: '#143828' },
  { id: 'ditie', term: '地鐵', isDeer: false, emoji: '🚇', badge: '', plate: '#1a3050' },
  { id: 'motuoche', term: '摩托車', isDeer: false, emoji: '🏍️', badge: '', plate: '#2a2a35' },
  { id: 'xiaofangche', term: '消防車', isDeer: false, emoji: '🚒', badge: '', plate: '#401018' },
  { id: 'jiuhuche', term: '救護車', isDeer: false, emoji: '🚑', badge: '', plate: '#2a3a50' },
  { id: 'jingche', term: '警察車', isDeer: false, emoji: '🚓', badge: '', plate: '#102848' },
  // 身體
  { id: 'yan', term: '眼睛', isDeer: false, emoji: '👀', badge: '', plate: '#2a3548' },
  { id: 'erduo', term: '耳朵', isDeer: false, emoji: '👂', badge: '', plate: '#3a2818' },
  { id: 'bi', term: '鼻子', isDeer: false, emoji: '👃', badge: '', plate: '#3a2818' },
  { id: 'kou', term: '嘴巴', isDeer: false, emoji: '👄', badge: '', plate: '#401028' },
  { id: 'shou', term: '手', isDeer: false, emoji: '✋', badge: '', plate: '#3a3010' },
  { id: 'jiao', term: '腳', isDeer: false, emoji: '🦶', badge: '', plate: '#3a2818' },
  { id: 'tou', term: '頭', isDeer: false, emoji: '🗣️', badge: '', plate: '#2a3548' },
  { id: 'xin', term: '心', isDeer: false, emoji: '❤️', badge: '', plate: '#401018' },
  // 情緒
  { id: 'kaixin', term: '開心', isDeer: false, emoji: '😊', badge: '', plate: '#3a3010' },
  { id: 'bukaixin', term: '不開心', isDeer: false, emoji: '😢', badge: '', plate: '#1a3050' },
  { id: 'shengqi', term: '生氣', isDeer: false, emoji: '😠', badge: '', plate: '#401018' },
  { id: 'haipa', term: '害怕', isDeer: false, emoji: '😨', badge: '', plate: '#2a1840' },
  { id: 'jingxi', term: '驚喜', isDeer: false, emoji: '😲', badge: '', plate: '#3a3410' },
  { id: 'haixiu', term: '害羞', isDeer: false, emoji: '🫣', badge: '', plate: '#402038' },
  // 身體感覺
  { id: 'lei', term: '累', isDeer: false, emoji: '😩', badge: '', plate: '#2a2a35' },
  { id: 'e_hungry', term: '餓', isDeer: false, emoji: '😋', badge: '', plate: '#402410' },
  { id: 'bao_full', term: '飽', isDeer: false, emoji: '😌', badge: '飽', plate: '#143828' },
  { id: 'ke_thirsty', term: '渴', isDeer: false, emoji: '🥤', badge: '', plate: '#0f3550' },
  { id: 'tong', term: '痛', isDeer: false, emoji: '😣', badge: '', plate: '#401820' },
  { id: 're_hot', term: '熱', isDeer: false, emoji: '🥵', badge: '', plate: '#402010' },
  { id: 'leng_cold', term: '冷', isDeer: false, emoji: '🥶', badge: '', plate: '#102848' },
  { id: 'xiang_scent', term: '香', isDeer: false, emoji: '👃', badge: '香', plate: '#402038' },
  { id: 'chou', term: '臭', isDeer: false, emoji: '🤢', badge: '💩', plate: '#2a3810' },
  // 家庭
  { id: 'baba', term: '爸爸', isDeer: false, emoji: '👨', badge: '', plate: '#1a3050' },
  { id: 'mama', term: '媽媽', isDeer: false, emoji: '👩', badge: '', plate: '#402038' },
  { id: 'yeye', term: '爺爺', isDeer: false, emoji: '👴', badge: '', plate: '#2a3548' },
  { id: 'popo', term: '婆婆', isDeer: false, emoji: '👵', badge: '', plate: '#3a2a40' },
  { id: 'gege', term: '哥哥', isDeer: false, emoji: '👦', badge: '', plate: '#102848' },
  { id: 'jiejie', term: '姐姐', isDeer: false, emoji: '👧', badge: '', plate: '#402038' },
  { id: 'baobao', term: '寶寶', isDeer: false, emoji: '👶', badge: '', plate: '#3a3010' },
  // 食物（非蔬果）
  { id: 'fan', term: '白飯', isDeer: false, emoji: '🍚', badge: '', plate: '#2a3548' },
  { id: 'mian', term: '湯麵', isDeer: false, emoji: '🍜', badge: '', plate: '#3a3010' },
  { id: 'bao', term: '麵包', isDeer: false, emoji: '🍞', badge: '', plate: '#3a2818' },
  { id: 'dan', term: '蛋', isDeer: false, emoji: '🥚', badge: '', plate: '#3a3a45' },
  { id: 'nai', term: '牛奶', isDeer: false, emoji: '🥛', badge: '', plate: '#2a3a50' },
  { id: 'dangao', term: '蛋糕', isDeer: false, emoji: '🎂', badge: '', plate: '#402038' },
  { id: 'shui', term: '水', isDeer: false, emoji: '💧', badge: '', plate: '#0f3550' },
  { id: 'guozhi', term: '果汁', isDeer: false, emoji: '🧃', badge: '', plate: '#402410' },
  { id: 'xuegao', term: '雪糕', isDeer: false, emoji: '🍦', badge: '', plate: '#402038' },
  { id: 'binggan', term: '餅乾', isDeer: false, emoji: '🍪', badge: '', plate: '#3a2818' },
  { id: 'tangguo', term: '糖果', isDeer: false, emoji: '🍬', badge: '', plate: '#2a1840' },
  { id: 'hanbao', term: '漢堡包', isDeer: false, emoji: '🍔', badge: '', plate: '#3a3010' },
  { id: 'pisa', term: '薄餅', isDeer: false, emoji: '🍕', badge: '', plate: '#401820' },
  { id: 'shutiao', term: '薯條', isDeer: false, emoji: '🍟', badge: '', plate: '#3a3010' },
  { id: 'sanwenzi', term: '三文治', isDeer: false, emoji: '🥪', badge: '', plate: '#3a3010' },
  { id: 'jirou', term: '雞肉', isDeer: false, emoji: '🍗', badge: '', plate: '#402010' },
  { id: 'niurou', term: '牛肉', isDeer: false, emoji: '🥩', badge: '牛', plate: '#401820', photo: 'assets/food/niurou.jpg' },
  { id: 'zhurou', term: '豬肉', isDeer: false, emoji: '🥓', badge: '豬', plate: '#402030', photo: 'assets/food/zhurou.jpg' },
  { id: 'yangrou', term: '羊肉', isDeer: false, emoji: '🍖', badge: '羊', plate: '#3a2818', photo: 'assets/food/yangrou.jpg' },
  { id: 'feiniu', term: '肥牛', isDeer: false, emoji: '🥩', badge: '', plate: '#401820', photo: 'assets/food/feiniu.jpg' },
  { id: 'xia_shrimp', term: '蝦', isDeer: false, emoji: '🦐', badge: '', plate: '#401028' },
  { id: 'xie_crab', term: '蟹', isDeer: false, emoji: '🦀', badge: '', plate: '#401820' },
  // 海鮮：唔用 🦞（龍蝦），用雙 emoji 表達「好多種海味」
  { id: 'haixian', term: '海鮮', isDeer: false, emoji: '🦐🐟', emojiDuo: true, badge: '', plate: '#0f3550' },
  // 學校／用品
  { id: 'shu', term: '書本', isDeer: false, emoji: '📚', badge: '', plate: '#102848' },
  { id: 'gangbi', term: '鉛筆', isDeer: false, emoji: '✏️', badge: '', plate: '#3a3010' },
  { id: 'chi', term: '間尺', isDeer: false, emoji: '📏', badge: '', plate: '#2a3548' },
  { id: 'shubao', term: '書包', isDeer: false, emoji: '🎒', badge: '', plate: '#401820' },
  { id: 'qiu', term: '足球', isDeer: false, emoji: '⚽', badge: '', plate: '#143820' },
  { id: 'jimu', term: '積木', isDeer: false, emoji: '🧸', badge: '', plate: '#3a2818' },
  // 地方（屋用 wuzi，避免同數字「五」id wu 撞車）
  { id: 'wuzi', term: '屋企', isDeer: false, emoji: '🏠', badge: '', plate: '#1a3050' },
  { id: 'xuexiao', term: '學校', isDeer: false, emoji: '🏫', badge: '', plate: '#102848' },
  { id: 'gongyuan', term: '公園', isDeer: false, emoji: '🛝', badge: '', plate: '#143828' },
  { id: 'shangchang', term: '商場', isDeer: false, emoji: '🏬', badge: '', plate: '#401820' },
  { id: 'tushuguan', term: '圖書館', isDeer: false, emoji: '📖', badge: '', plate: '#1a3050' },
  { id: 'tingchechang', term: '停車場', isDeer: false, emoji: '🅿️', badge: '', plate: '#2a3548' },
  { id: 'shatian', term: '沙田', isDeer: false, emoji: '🏢', badge: '', plate: '#3a3010' },
  { id: 'yiyuan', term: '醫院', isDeer: false, emoji: '🏥', badge: '', plate: '#2a3a50' },
  { id: 'xiaofangju', term: '消防局', isDeer: false, emoji: '🚒', badge: '🏠', plate: '#401820' },
  { id: 'jingchaju', term: '警察局', isDeer: false, emoji: '🚓', badge: '🏠', plate: '#102848' },
  { id: 'jichang', term: '機場', isDeer: false, emoji: '🛫', badge: '', plate: '#1a3050' },
  { id: 'haitan', term: '海灘', isDeer: false, emoji: '🏖️', badge: '', plate: '#0f3550' },
  { id: 'canting', term: '餐廳', isDeer: false, emoji: '🍽️', badge: '', plate: '#3a3010' },
  { id: 'jieshi', term: '街市', isDeer: false, emoji: '🛒', badge: '', plate: '#143828' },
  { id: 'youlechang', term: '遊樂場', isDeer: false, emoji: '🎠', badge: '', plate: '#402038' },
  { id: 'chaoshi', term: '超市', isDeer: false, emoji: '🏪', badge: '', plate: '#3a3010' },
  { id: 'keshi', term: '課室', isDeer: false, emoji: '🏫', badge: '課', plate: '#1a3050' },
  { id: 'yongchi', term: '泳池', isDeer: false, emoji: '🏊', badge: '', plate: '#0f3550' },
  // 屋企：房間／傢俬／電器／設施（叫法跟朋友：沙發、冰箱、電風扇、床、窗戶、門）
  { id: 'chufang', term: '廚房', isDeer: false, emoji: '🍳', badge: '', plate: '#3a3010' },
  { id: 'shuifang', term: '睡房', isDeer: false, emoji: '🛏️', badge: '房', plate: '#1a3050' },
  { id: 'cesuo', term: '廁所', isDeer: false, emoji: '🚽', badge: '', plate: '#2a3548' },
  { id: 'yushi', term: '浴室', isDeer: false, emoji: '🚿', badge: '', plate: '#0f3550' },
  { id: 'dianshi', term: '電視', isDeer: false, emoji: '📺', badge: '', plate: '#102848' },
  { id: 'xuegui', term: '冰箱', isDeer: false, emoji: '🧊', badge: '', plate: '#0f3550' },
  { id: 'xiyiji', term: '洗衣機', isDeer: false, emoji: '🧺', badge: '', plate: '#1a3050' },
  { id: 'dianhua', term: '電話', isDeer: false, emoji: '📱', badge: '', plate: '#2a2a35' },
  { id: 'fengshan', term: '電風扇', isDeer: false, emoji: '🌬️', badge: '', plate: '#243848' },
  { id: 'men', term: '門', isDeer: false, emoji: '🚪', badge: '', plate: '#3a2818' },
  { id: 'chuanghu', term: '窗戶', isDeer: false, emoji: '🪟', badge: '', plate: '#0f3550' },
  { id: 'deng', term: '燈', isDeer: false, emoji: '💡', badge: '', plate: '#3a3410' },
  { id: 'yizi', term: '椅子', isDeer: false, emoji: '🪑', badge: '', plate: '#3a2818' },
  { id: 'zhuozi', term: '桌子', isDeer: false, emoji: '🪑', badge: '桌', plate: '#2a3548' },
  { id: 'yigui', term: '衣櫃', isDeer: false, emoji: '👕', badge: '', plate: '#1a3050' },
  { id: 'tuoxie', term: '拖鞋', isDeer: false, emoji: '🩴', badge: '', plate: '#402038' },
  { id: 'chuangpu', term: '床', isDeer: false, emoji: '🛏️', badge: '', plate: '#1a2a4a' },
  { id: 'shafa', term: '沙發', isDeer: false, emoji: '🛋️', badge: '', plate: '#281840' },
  { id: 'zhentou', term: '枕頭', isDeer: false, emoji: '🛏️', badge: '枕', plate: '#2a1840' },
  { id: 'beizi', term: '被子', isDeer: false, emoji: '🛏️', badge: '被', plate: '#401028' },
  { id: 'shizhong', term: '時鐘', isDeer: false, emoji: '⏰', badge: '', plate: '#3a3010' },
  { id: 'lengqi', term: '冷氣機', isDeer: false, emoji: '❄️', badge: '冷', plate: '#0f3550' },
  { id: 'mensuo', term: '門鎖', isDeer: false, emoji: '🔒', badge: '', plate: '#2a2a35' },
  { id: 'lajitong', term: '垃圾桶', isDeer: false, emoji: '🗑️', badge: '', plate: '#3a3a45' },
  { id: 'xiangkuang', term: '相框', isDeer: false, emoji: '🖼️', badge: '', plate: '#3a2818' },
  { id: 'ditan', term: '地毯', isDeer: false, emoji: '🟫', badge: '', plate: '#402010', en: { word: 'mat', letters: ['m', 'a', 't'] } },
  { id: 'xishoutai', term: '洗手台', isDeer: false, emoji: '🧼', badge: '台', plate: '#2a3a50' },
  { id: 'shuilongtou', term: '水龍頭', isDeer: false, emoji: '🚰', badge: '', plate: '#102848' },
  { id: 'chouti', term: '抽屜', isDeer: false, emoji: '🗄️', badge: '', plate: '#3a2818' },
  { id: 'yangtai', term: '陽台', isDeer: false, emoji: '🪴', badge: '', plate: '#143828' },
  // 日常用品（含餐具；鏡子／毛巾／牙刷由屋企移入）
  { id: 'jing', term: '鏡子', isDeer: false, emoji: '🪞', badge: '', plate: '#2a3a50' },
  { id: 'maojin', term: '毛巾', isDeer: false, emoji: '🧼', badge: '巾', plate: '#2a3a50' },
  { id: 'yashua', term: '牙刷', isDeer: false, emoji: '🪥', badge: '', plate: '#143828' },
  { id: 'shuihu', term: '水壺', isDeer: false, emoji: '🥤', badge: '', plate: '#0f3550' },
  { id: 'yagao', term: '牙膏', isDeer: false, emoji: '🦷', badge: '膏', plate: '#2a3a50' },
  { id: 'beizi_cup', term: '杯子', isDeer: false, emoji: '🥤', badge: '', plate: '#102848' },
  { id: 'wan', term: '碗', isDeer: false, emoji: '🥣', badge: '', plate: '#3a3010' },
  { id: 'tangchi', term: '湯匙', isDeer: false, emoji: '🥄', badge: '', plate: '#2a3548' },
  { id: 'kuaizi', term: '筷子', isDeer: false, emoji: '🥢', badge: '', plate: '#3a2818' },
  { id: 'chazi', term: '叉子', isDeer: false, emoji: '🍴', badge: '', plate: '#401820' },
  { id: 'panzi', term: '盤子', isDeer: false, emoji: '🍽️', badge: '', plate: '#1a3050' },
  { id: 'zhijin', term: '紙巾', isDeer: false, emoji: '🧻', badge: '', plate: '#3a3a45' },
  { id: 'shuzi', term: '梳子', isDeer: false, emoji: '🪮', badge: '', plate: '#402038' },
  { id: 'lifa', term: '理髮', isDeer: false, emoji: '💇', badge: '', plate: '#281840' },
  { id: 'xitoushui', term: '洗頭水', isDeer: false, emoji: '🧴', badge: '洗', plate: '#1a3050' },
  { id: 'muyulu', term: '沐浴露', isDeer: false, emoji: '🧴', badge: '浴', plate: '#0f3535' },
  { id: 'kouzhao', term: '口罩', isDeer: false, emoji: '😷', badge: '', plate: '#2a3548' },
  { id: 'yanjing', term: '眼鏡', isDeer: false, emoji: '👓', badge: '', plate: '#1a2a4a' },
  // 紅輯高頻（對齊《我自己會讀》紅輯溫習；書面語字形，粵語 TTS）
  // 注意：間尺已用 id chi，故「吃」用 chi_eat；數字「十」已用 shi，故「是」用 shi_be
  { id: 'wo', term: '我', isDeer: false, emoji: '🙋', badge: '', plate: '#1a3050' },
  { id: 'ni', term: '你', isDeer: false, emoji: '👉', badge: '', plate: '#102848' },
  { id: 'ta_he', term: '他', isDeer: false, emoji: '👨', badge: '他', plate: '#2a3548' },
  { id: 'ta_she', term: '她', isDeer: false, emoji: '👩', badge: '她', plate: '#402038' },
  { id: 'kan', term: '看', isDeer: false, emoji: '👀', badge: '看', plate: '#2a1840' },
  { id: 'lai', term: '來', isDeer: false, emoji: '➡️', badge: '', plate: '#143828' },
  { id: 'qu', term: '去', isDeer: false, emoji: '⬅️', badge: '', plate: '#3a3010' },
  { id: 'chi_eat', term: '吃', isDeer: false, emoji: '🍽️', badge: '', plate: '#401820' },
  { id: 'wan_play', term: '玩', isDeer: false, emoji: '🎲', badge: '', plate: '#281840' },
  { id: 'pao', term: '跑', isDeer: false, emoji: '🏃', badge: '', plate: '#402010' },
  { id: 'zou', term: '走', isDeer: false, emoji: '🚶', badge: '', plate: '#2a2a35' },
  { id: 'zuo_sit', term: '坐', isDeer: false, emoji: '🪑', badge: '坐', plate: '#3a2818' },
  { id: 'da_big', term: '大', isDeer: false, emoji: '⬛', badge: '', plate: '#1a1a22' },
  { id: 'xiao_small', term: '小', isDeer: false, emoji: '🔸', badge: '', plate: '#3a3a45' },
  { id: 'you_have', term: '有', isDeer: false, emoji: '✋', badge: '有', plate: '#143820' },
  { id: 'zai', term: '在', isDeer: false, emoji: '📍', badge: '', plate: '#401018' },
  { id: 'shi_be', term: '是', isDeer: false, emoji: '✔️', badge: '', plate: '#0f3535' },
  { id: 'bu', term: '不', isDeer: false, emoji: '❌', badge: '', plate: '#401018' },
  { id: 'hao', term: '好', isDeer: false, emoji: '👍', badge: '', plate: '#143828' },
  { id: 'shang', term: '上', isDeer: false, emoji: '⬆️', badge: '', plate: '#1a3050' },
  { id: 'xia', term: '下', isDeer: false, emoji: '⬇️', badge: '', plate: '#102848' },
  { id: 'ai_love', term: '愛', isDeer: false, emoji: '💗', badge: '', plate: '#401028' },
  { id: 'gei', term: '給', isDeer: false, emoji: '🎁', badge: '', plate: '#2a1840' },
  { id: 'zhao', term: '找', isDeer: false, emoji: '🔍', badge: '', plate: '#2a3548' },
  { id: 'shuo', term: '說', isDeer: false, emoji: '💬', badge: '', plate: '#1a3050' },
  { id: 'pengyou', term: '朋友', isDeer: false, emoji: '👫', badge: '', plate: '#402038' },
  { id: 'zhe', term: '這', isDeer: false, emoji: '👇', badge: '', plate: '#3a3010' },
  { id: 'na_that', term: '那', isDeer: false, emoji: '👉', badge: '那', plate: '#2a2a35' },
  { id: 'duo', term: '多', isDeer: false, emoji: '🔢', badge: '多', plate: '#102848' },
  { id: 'shao', term: '少', isDeer: false, emoji: '1️⃣', badge: '少', plate: '#2a3548' },
  { id: 'didi', term: '弟弟', isDeer: false, emoji: '👦', badge: '弟', plate: '#1a3050' },
  { id: 'meimei', term: '妹妹', isDeer: false, emoji: '👧', badge: '妹', plate: '#402038' },
  { id: 'shuijiao', term: '睡覺', isDeer: false, emoji: '😴', badge: '', plate: '#1a2a4a' },
  { id: 'xiexie', term: '謝謝', isDeer: false, emoji: '🙏', badge: '', plate: '#3a3010' },
  { id: 'laoshi', term: '老師', isDeer: false, emoji: '👩‍🏫', badge: '', plate: '#102848' },
  { id: 'shu_book', term: '書', isDeer: false, emoji: '📕', badge: '', plate: '#401820' },
  // 港式美食（用真實相；emoji 係 fallback）
  { id: 'feiniu_wudong', term: '肥牛烏冬', isDeer: false, emoji: '🍜', badge: '', plate: '#3a3010', photo: 'assets/food-hk/feiniu-wudong.jpg' },
  { id: 'gulourou', term: '咕嚕肉', isDeer: false, emoji: '🍖', badge: '', plate: '#401820', photo: 'assets/food-hk/gulourou.jpg' },
  { id: 'dabianlu', term: '打邊爐', isDeer: false, emoji: '🍲', badge: '', plate: '#401018', photo: 'assets/food-hk/dabianlu.jpg' },
  { id: 'yezi', term: '椰子', isDeer: false, emoji: '🥥', badge: '', plate: '#3a2818', photo: 'assets/food-hk/yezi.jpg' },
  { id: 'maileji', term: '麥樂雞', isDeer: false, emoji: '🍗', badge: '', plate: '#3a3010', photo: 'assets/food-hk/maileji.jpg' },
  { id: 'roujiang_yifen', term: '肉醬意粉', isDeer: false, emoji: '🍝', badge: '', plate: '#401820', photo: 'assets/food-hk/roujiang-yifen.jpg' },
  { id: 'wonton_mian', term: '雲吞麵', isDeer: false, emoji: '🍜', badge: '', plate: '#3a3010', photo: 'assets/food-hk/wonton-mian.jpg' },
  { id: 'changfen', term: '腸粉', isDeer: false, emoji: '🍚', badge: '', plate: '#2a3548', photo: 'assets/food-hk/changfen.jpg' },
  { id: 'siumai', term: '燒賣', isDeer: false, emoji: '🥟', badge: '', plate: '#3a3010', photo: 'assets/food-hk/siumai.jpg' },
  { id: 'yudan', term: '魚蛋', isDeer: false, emoji: '🍢', badge: '', plate: '#3a3010', photo: 'assets/food-hk/yudan.jpg' },
  { id: 'naicha', term: '奶茶', isDeer: false, emoji: '🧋', badge: '', plate: '#3a2818', photo: 'assets/food-hk/naicha.jpg' },
  { id: 'boluoyou', term: '菠蘿油', isDeer: false, emoji: '🍍', badge: '', plate: '#3a3410', photo: 'assets/food-hk/boluoyou.jpg' },
  { id: 'fanqie_chaodan', term: '蕃茄炒蛋', isDeer: false, emoji: '🍅', badge: '', plate: '#401820', photo: 'assets/food-hk/fanqie-chaodan.jpg' },
  { id: 'zheng_yu', term: '蒸魚', isDeer: false, emoji: '🐟', badge: '', plate: '#0f3550', photo: 'assets/food-hk/zheng-yu.jpg' },
  { id: 'zheng_shuidan', term: '蒸水蛋', isDeer: false, emoji: '🥚', badge: '', plate: '#3a3a45', photo: 'assets/food-hk/zheng-shuidan.jpg' },
  // 職業
  { id: 'yisheng', term: '醫生', isDeer: false, emoji: '👨‍⚕️', badge: '', plate: '#102848' },
  { id: 'hushi', term: '護士', isDeer: false, emoji: '👩‍⚕️', badge: '', plate: '#402038' },
  { id: 'laoshi_job', term: '老師', isDeer: false, emoji: '👩‍🏫', badge: '', plate: '#102848' },
  { id: 'xiaofangyuan', term: '消防員', isDeer: false, emoji: '🧑‍🚒', badge: '', plate: '#401820' },
  { id: 'jingcha', term: '警察', isDeer: false, emoji: '👮', badge: '', plate: '#102848' },
  { id: 'chushi', term: '廚師', isDeer: false, emoji: '🧑‍🍳', badge: '', plate: '#3a3010' },
  { id: 'siji', term: '司機', isDeer: false, emoji: '🚗', badge: '', plate: '#1a3050' },
  { id: 'nongfu', term: '農夫', isDeer: false, emoji: '🧑‍🌾', badge: '', plate: '#143828' },
  { id: 'jishi', term: '機師', isDeer: false, emoji: '✈️🧑‍✈️', emojiDuo: true, badge: '', plate: '#1a3050' },
  { id: 'kongjie', term: '空姐', isDeer: false, emoji: '✈️👩‍✈️', emojiDuo: true, badge: '', plate: '#102848' },
  { id: 'taikongren', term: '太空人', isDeer: false, emoji: '🚀🧑‍🚀', emojiDuo: true, badge: '', plate: '#1a1a22' },
  { id: 'yayi', term: '牙醫', isDeer: false, emoji: '🦷👨‍⚕️', emojiDuo: true, badge: '', plate: '#102848' },
  { id: 'shouyi', term: '獸醫', isDeer: false, emoji: '🐶👨‍⚕️', emojiDuo: true, badge: '', plate: '#1a4d3a' },
  { id: 'kexuejia', term: '科學家', isDeer: false, emoji: '🔬🧑‍🔬', emojiDuo: true, badge: '', plate: '#0f3550' },
  { id: 'huajia', term: '畫家', isDeer: false, emoji: '🎨🖌️', emojiDuo: true, badge: '', plate: '#402038' },
  { id: 'yinyuejia', term: '音樂家', isDeer: false, emoji: '🎵🧑‍🎤', emojiDuo: true, badge: '', plate: '#2a1840' },
  { id: 'yundongyuan', term: '運動員', isDeer: false, emoji: '🏃🏅', emojiDuo: true, badge: '', plate: '#143828' },
  { id: 'bashi_siji', term: '巴士司機', isDeer: false, emoji: '🚌🧑‍✈️', emojiDuo: true, badge: '', plate: '#3a3010' },
  { id: 'jianzhu_gongren', term: '建築工人', isDeer: false, emoji: '👷🏗️', emojiDuo: true, badge: '', plate: '#3a3010' },
  { id: 'faxingshi', term: '髮型師', isDeer: false, emoji: '💇✂️', emojiDuo: true, badge: '', plate: '#402038' },
  { id: 'huanbao_zhuren', term: '環境保護主任', isDeer: false, emoji: '♻️👮', emojiDuo: true, badge: '', plate: '#143828' },
  { id: 'yiliao_xiaoshou', term: '醫療銷售代表', isDeer: false, emoji: '💊🤝', emojiDuo: true, badge: '', plate: '#102848' },
  // 恐龍（彩色復原圖；emoji 係 fallback）
  { id: 'konglong', term: '恐龍', isDeer: false, emoji: '🦕', badge: '', plate: '#1a4d3a' },
  { id: 'baolong', term: '暴龍', isDeer: false, emoji: '🦖', badge: '', plate: '#3a2818', photo: 'assets/dino/baolong.jpg' },
  { id: 'sanjiaolong', term: '三角龍', isDeer: false, emoji: '🦕', badge: '三', plate: '#2a3548', photo: 'assets/dino/sanjiaolong.jpg' },
  { id: 'lianglong', term: '梁龍', isDeer: false, emoji: '🦕', badge: '梁', plate: '#1a4d3a', photo: 'assets/dino/lianglong.jpg' },
  { id: 'jianlong', term: '劍龍', isDeer: false, emoji: '🦕', badge: '劍', plate: '#2a2a35', photo: 'assets/dino/jianlong.jpg' },
  { id: 'yilong', term: '翼龍', isDeer: false, emoji: '🦅', badge: '翼', plate: '#102848', photo: 'assets/dino/yilong.jpg' },
  { id: 'konglongdan', term: '恐龍蛋', isDeer: false, emoji: '🥚', badge: '恐', plate: '#3a3010' },
  { id: 'fuzhilong', term: '副櫛龍', isDeer: false, emoji: '🦕', badge: '冠', plate: '#2a3548', photo: 'assets/dino/fuzhilong.jpg' },
  { id: 'jialong', term: '甲龍', isDeer: false, emoji: '🦕', badge: '甲', plate: '#3a2818', photo: 'assets/dino/jialong.jpg' },
  { id: 'sulong', term: '速龍', isDeer: false, emoji: '🦖', badge: '速', plate: '#1a3050', photo: 'assets/dino/sulong.jpg' },
  // 昆蟲小生物
  { id: 'hudie', term: '蝴蝶', isDeer: false, emoji: '🦋', badge: '', plate: '#402038' },
  { id: 'mifeng', term: '蜜蜂', isDeer: false, emoji: '🐝', badge: '', plate: '#3a3410' },
  { id: 'mayi', term: '螞蟻', isDeer: false, emoji: '🐜', badge: '', plate: '#2a3810' },
  { id: 'jiachong', term: '甲蟲', isDeer: false, emoji: '🪲', badge: '', plate: '#143828' },
  { id: 'zhizhu', term: '蜘蛛', isDeer: false, emoji: '🕷️', badge: '', plate: '#1a1a22' },
  { id: 'woniu', term: '蝸牛', isDeer: false, emoji: '🐌', badge: '', plate: '#3a2818' },
  { id: 'maomaochong', term: '毛毛蟲', isDeer: false, emoji: '🐛', badge: '', plate: '#2a3810' },
  { id: 'qingting', term: '蜻蜓', isDeer: false, emoji: '🪽', badge: '蜻', plate: '#0f3550' },
  // 海洋動物
  { id: 'shayu', term: '鯊魚', isDeer: false, emoji: '🦈', badge: '', plate: '#0f3550' },
  { id: 'jingyu', term: '鯨魚', isDeer: false, emoji: '🐋', badge: '', plate: '#102848' },
  { id: 'bazhaoyu', term: '八爪魚', isDeer: false, emoji: '🐙', badge: '', plate: '#402038' },
  { id: 'shuimu', term: '水母', isDeer: false, emoji: '🪼', badge: '', plate: '#2a1840' },
  { id: 'haigui', term: '海龜', isDeer: false, emoji: '🐢', badge: '', plate: '#143828' },
  { id: 'haixing', term: '海星', isDeer: false, emoji: '⭐', badge: '海', plate: '#3a3010' },
  { id: 'xiaochouyu', term: '小丑魚', isDeer: false, emoji: '🐠', badge: '丑', plate: '#401820' },
  { id: 'youyu', term: '魷魚', isDeer: false, emoji: '🦑', badge: '', plate: '#0f3550' },
  // 衣物
  { id: 'shan', term: '衫', isDeer: false, emoji: '👕', badge: '', plate: '#3a3010' },
  { id: 'fu', term: '褲', isDeer: false, emoji: '👖', badge: '', plate: '#102848' },
  { id: 'kwan', term: '裙', isDeer: false, emoji: '👗', badge: '', plate: '#402038' },
  { id: 'haai', term: '鞋', isDeer: false, emoji: '👟', badge: '', plate: '#2a3548' },
  { id: 'mat', term: '襪', isDeer: false, emoji: '🧦', badge: '', plate: '#401820' },
  { id: 'mou', term: '帽', isDeer: false, emoji: '🧢', badge: '', plate: '#1a3050' },
  { id: 'waihgan', term: '頸巾', isDeer: false, emoji: '🧣', badge: '', plate: '#401018' },
  { id: 'shoutao', term: '手套', isDeer: false, emoji: '🧤', badge: '', plate: '#3a2818' },
  // 相反／空間（主題 opposites；大／小／多／少／上／下同紅輯共用）
  { id: 'chang_long', term: '長', isDeer: false, emoji: '📏', badge: '長', plate: '#1a3050' },
  { id: 'duan_short', term: '短', isDeer: false, emoji: '✏️', badge: '短', plate: '#3a3010' },
  { id: 'gao_tall', term: '高', isDeer: false, emoji: '🦒', badge: '高', plate: '#3a3010' },
  { id: 'ai_short_height', term: '矮', isDeer: false, emoji: '🐣', badge: '矮', plate: '#402038' },
  { id: 'qian_front', term: '前', isDeer: false, emoji: '🚶', badge: '前', plate: '#143828' },
  { id: 'hou_back', term: '後', isDeer: false, emoji: '🔙', badge: '後', plate: '#2a2a35' },
  { id: 'zuo_left', term: '左', isDeer: false, emoji: '👈', badge: '', plate: '#102848' },
  { id: 'you_right', term: '右', isDeer: false, emoji: '👉', badge: '', plate: '#401820' },
  { id: 'limian', term: '裏面', isDeer: false, emoji: '🏠', badge: '裏', plate: '#1a3050' },
  { id: 'waimian', term: '外面', isDeer: false, emoji: '🚪', badge: '外', plate: '#0f3550' },
  // 紅輯擴充（對齊《我自己會讀》紅輯溫習字表）
  { id: 'women', term: '我們', isDeer: false, emoji: '👨‍👩‍👧‍👦', badge: '', plate: '#102848' },
  { id: 'nimen', term: '你們', isDeer: false, emoji: '🧑‍🤝‍🧑', badge: '', plate: '#2a3548' },
  { id: 'tamen', term: '他們', isDeer: false, emoji: '👥', badge: '', plate: '#1a3050' },
  { id: 'maamaa', term: '嫲嫲', isDeer: false, emoji: '👵', badge: '嫲', plate: '#402038' },
  { id: 'gonggong', term: '公公', isDeer: false, emoji: '👴', badge: '公', plate: '#2a3548' },
  { id: 'tongxue', term: '同學', isDeer: false, emoji: '🧑‍🎓', badge: '', plate: '#102848' },
  { id: 'dajia', term: '大家', isDeer: false, emoji: '👨‍👩‍👧‍👦', badge: '', plate: '#143828' },
  { id: 'ziji', term: '自己', isDeer: false, emoji: '🪞', badge: '', plate: '#2a1840' },
  { id: 'kanjian', term: '看見', isDeer: false, emoji: '👀', badge: '', plate: '#2a1840' },
  { id: 'tingjian', term: '聽見', isDeer: false, emoji: '👂', badge: '', plate: '#3a2818' },
  { id: 'du', term: '讀', isDeer: false, emoji: '📖', badge: '', plate: '#1a3050' },
  { id: 'xie', term: '寫', isDeer: false, emoji: '✍️', badge: '', plate: '#2a3548' },
  { id: 'hua_draw', term: '畫', isDeer: false, emoji: '🎨', badge: '', plate: '#402038' },
  { id: 'chang_sing', term: '唱', isDeer: false, emoji: '🎤', badge: '', plate: '#2a1840' },
  { id: 'hui', term: '回', isDeer: false, emoji: '🔙', badge: '', plate: '#143828' },
  { id: 'chu', term: '出', isDeer: false, emoji: '📤', badge: '', plate: '#3a3010' },
  { id: 'ru', term: '入', isDeer: false, emoji: '📥', badge: '', plate: '#102848' },
  { id: 'zhan', term: '站', isDeer: false, emoji: '🧍', badge: '', plate: '#2a2a35' },
  { id: 'tiao', term: '跳', isDeer: false, emoji: '🤸', badge: '', plate: '#143820' },
  { id: 'fei', term: '飛', isDeer: false, emoji: '🕊️', badge: '', plate: '#1a3050' },
  { id: 'you_swim', term: '游', isDeer: false, emoji: '🏊', badge: '', plate: '#0f3550' },
  { id: 'pa', term: '爬', isDeer: false, emoji: '🧗', badge: '', plate: '#3a2818' },
  { id: 'he_drink', term: '喝', isDeer: false, emoji: '🥤', badge: '', plate: '#402410' },
  { id: 'shui_sleep', term: '睡', isDeer: false, emoji: '😴', badge: '', plate: '#1a2a4a' },
  { id: 'xing', term: '醒', isDeer: false, emoji: '⏰', badge: '', plate: '#3a3010' },
  { id: 'xi', term: '洗', isDeer: false, emoji: '🛁', badge: '', plate: '#0f3550' },
  { id: 'chuan_wear', term: '穿', isDeer: false, emoji: '👕', badge: '穿', plate: '#3a3010' },
  { id: 'tuo', term: '脫', isDeer: false, emoji: '👕', badge: '脫', plate: '#402030' },
  { id: 'kai', term: '開', isDeer: false, emoji: '🔓', badge: '', plate: '#143828' },
  { id: 'guan', term: '關', isDeer: false, emoji: '🔒', badge: '', plate: '#401018' },
  { id: 'na_take', term: '拿', isDeer: false, emoji: '🫴', badge: '', plate: '#3a2818' },
  { id: 'fang', term: '放', isDeer: false, emoji: '🫳', badge: '', plate: '#2a3548' },
  { id: 'xiao_laugh', term: '笑', isDeer: false, emoji: '😄', badge: '', plate: '#3a3410' },
  { id: 'ku', term: '哭', isDeer: false, emoji: '😢', badge: '', plate: '#102848' },
  { id: 'bao_hug', term: '抱', isDeer: false, emoji: '🤗', badge: '', plate: '#402038' },
  { id: 'xiang_think', term: '想', isDeer: false, emoji: '💭', badge: '', plate: '#2a1840' },
  { id: 'yao_want', term: '要', isDeer: false, emoji: '🙋', badge: '', plate: '#3a3010' },
  { id: 'huai', term: '壞', isDeer: false, emoji: '👎', badge: '', plate: '#401018' },
  { id: 'kuai', term: '快', isDeer: false, emoji: '⚡', badge: '', plate: '#3a3410' },
  { id: 'man', term: '慢', isDeer: false, emoji: '🐢', badge: '', plate: '#143828' },
  { id: 'xin_new', term: '新', isDeer: false, emoji: '✨', badge: '', plate: '#3a3010' },
  { id: 'jiu_old', term: '舊', isDeer: false, emoji: '🕰️', badge: '', plate: '#2a2a35' },
  { id: 'tian', term: '甜', isDeer: false, emoji: '🍬', badge: '', plate: '#402038' },
  { id: 'guai', term: '乖', isDeer: false, emoji: '😇', badge: '', plate: '#143828' },
  { id: 'piaoliang', term: '漂亮', isDeer: false, emoji: '🌺', badge: '', plate: '#402038' },
  { id: 'de', term: '的', isDeer: false, emoji: '📌', badge: '', plate: '#2a3548' },
  { id: 'le', term: '了', isDeer: false, emoji: '✅', badge: '', plate: '#143828' },
  { id: 'ma_q', term: '嗎', isDeer: false, emoji: '❓', badge: '', plate: '#102848' },
  { id: 'ne', term: '呢', isDeer: false, emoji: '❔', badge: '', plate: '#2a2a35' },
  { id: 'he_and', term: '和', isDeer: false, emoji: '➕', badge: '', plate: '#3a3010' },
  { id: 'dou', term: '都', isDeer: false, emoji: '💯', badge: '', plate: '#401820' },
  { id: 'ye_also', term: '也', isDeer: false, emoji: '✌️', badge: '', plate: '#143820' },
  { id: 'you_again', term: '又', isDeer: false, emoji: '🔁', badge: '', plate: '#2a1840' },
  { id: 'zai_again', term: '再', isDeer: false, emoji: '🔂', badge: '', plate: '#1a3050' },
  { id: 'hen', term: '很', isDeer: false, emoji: '🆙', badge: '', plate: '#3a3010' },
  { id: 'meiyou', term: '沒有', isDeer: false, emoji: '🚫', badge: '', plate: '#401018' },
  { id: 'hui_can', term: '會', isDeer: false, emoji: '💪', badge: '', plate: '#143828' },
  { id: 'keyi', term: '可以', isDeer: false, emoji: '👍', badge: '', plate: '#143820' },
  { id: 'na_which', term: '哪', isDeer: false, emoji: '❓', badge: '哪', plate: '#102848' },
  { id: 'shenme', term: '什麼', isDeer: false, emoji: '🤔', badge: '', plate: '#2a3548' },
  { id: 'weishenme', term: '為什麼', isDeer: false, emoji: '🤷', badge: '', plate: '#401820' },
  { id: 'zenme', term: '怎麼', isDeer: false, emoji: '🧐', badge: '', plate: '#2a2a35' },
  { id: 'zheli', term: '這裏', isDeer: false, emoji: '📍👇', emojiDuo: true, badge: '', plate: '#1a3050' },
  { id: 'nali', term: '那裏', isDeer: false, emoji: '📍👉', emojiDuo: true, badge: '', plate: '#2a2a35' },
  { id: 'nali_where', term: '哪裏', isDeer: false, emoji: '📍❓', emojiDuo: true, badge: '', plate: '#102848' },
  { id: 'ge_mw', term: '個', isDeer: false, emoji: '1️⃣', badge: '個', plate: '#1a3050' },
  { id: 'zhi_mw', term: '隻', isDeer: false, emoji: '🐾', badge: '', plate: '#3a2818' },
  { id: 'ba_mw', term: '把', isDeer: false, emoji: '🖐️', badge: '', plate: '#3a3010' },
  { id: 'jintian', term: '今天', isDeer: false, emoji: '📅', badge: '', plate: '#102848' },
  { id: 'zuotian', term: '昨天', isDeer: false, emoji: '⏪', badge: '', plate: '#2a2a35' },
  { id: 'mingtian', term: '明天', isDeer: false, emoji: '⏩', badge: '', plate: '#1a3050' },
  { id: 'zaoshang', term: '早上', isDeer: false, emoji: '🌅', badge: '', plate: '#3a3410' },
  { id: 'xiawu', term: '下午', isDeer: false, emoji: '🌞', badge: '', plate: '#402410' },
  { id: 'wanshang', term: '晚上', isDeer: false, emoji: '🌃', badge: '', plate: '#1a2a4a' },
  { id: 'xianzai', term: '現在', isDeer: false, emoji: '▶️', badge: '', plate: '#143828' },
  { id: 'nian', term: '年', isDeer: false, emoji: '🎊', badge: '', plate: '#401820' },
  { id: 'yue_month', term: '月', isDeer: false, emoji: '🗓️', badge: '', plate: '#102848' },
  { id: 'ri_day', term: '日', isDeer: false, emoji: '📆', badge: '', plate: '#3a3010' },
  { id: 'xingqi', term: '星期', isDeer: false, emoji: '7️⃣', badge: '', plate: '#2a1840' },
  { id: 'shengri', term: '生日', isDeer: false, emoji: '🎉', badge: '', plate: '#401018' },
  { id: 'shan_mountain', term: '山', isDeer: false, emoji: '⛰️', badge: '', plate: '#2a3548' },
  { id: 'lian', term: '臉', isDeer: false, emoji: '🙂', badge: '', plate: '#3a2818' },
  { id: 'yachi', term: '牙齒', isDeer: false, emoji: '🦷', badge: '', plate: '#2a3548' },
  { id: 'shouzhi', term: '手指', isDeer: false, emoji: '☝️', badge: '', plate: '#3a3010' },
  { id: 'toufa', term: '頭髮', isDeer: false, emoji: '💇', badge: '', plate: '#402038' },
  { id: 'bi_pen', term: '筆', isDeer: false, emoji: '🖊️', badge: '', plate: '#3a3010' },
  { id: 'zhi_paper', term: '紙', isDeer: false, emoji: '📄', badge: '', plate: '#2a3548' },
  { id: 'wanju', term: '玩具', isDeer: false, emoji: '🪀', badge: '', plate: '#402038' },
  { id: 'qiu_ball', term: '球', isDeer: false, emoji: '🏀', badge: '', plate: '#3a3010' },
  { id: 'gongzai', term: '公仔', isDeer: false, emoji: '🪆', badge: '', plate: '#402038' },
  { id: 'yifu', term: '衣服', isDeer: false, emoji: '👔', badge: '', plate: '#102848' },
  { id: 'kuzi', term: '褲子', isDeer: false, emoji: '👖', badge: '', plate: '#102848' },
  { id: 'xiezi', term: '鞋子', isDeer: false, emoji: '👟', badge: '', plate: '#2a3548' },
  { id: 'wazi', term: '襪子', isDeer: false, emoji: '🧦', badge: '', plate: '#401820' },
  { id: 'maozi', term: '帽子', isDeer: false, emoji: '🧢', badge: '', plate: '#1a3050' },
  { id: 'miantiao', term: '麵條', isDeer: false, emoji: '🍜', badge: '', plate: '#3a3010' },
  { id: 'jidan', term: '雞蛋', isDeer: false, emoji: '🥚', badge: '', plate: '#3a3a45' },
  { id: 'xiaogou', term: '小狗', isDeer: false, emoji: '🐶', badge: '', plate: '#3a3010' },
  { id: 'xiaomao', term: '小貓', isDeer: false, emoji: '🐱', badge: '', plate: '#4a2030' },
  { id: 'xiaoyu', term: '小魚', isDeer: false, emoji: '🐟', badge: '', plate: '#0f3550' },
  { id: 'xiaoniao', term: '小鳥', isDeer: false, emoji: '🐦', badge: '', plate: '#1a3050' },
  { id: 'xiaoji', term: '小雞', isDeer: false, emoji: '🐤', badge: '', plate: '#402020' },
  { id: 'xiaoya', term: '小鴨', isDeer: false, emoji: '🐥', badge: '', plate: '#143828' },
  { id: 'xiaoma', term: '小馬', isDeer: false, emoji: '🐴', badge: '', plate: '#2a2520' },
  { id: 'xiaoniu', term: '小牛', isDeer: false, emoji: '🐮', badge: '', plate: '#3a3010' },
  { id: 'xiaoyang', term: '小羊', isDeer: false, emoji: '🐑', badge: '', plate: '#2a2a35' },
  { id: 'xiaozhu', term: '小豬', isDeer: false, emoji: '🐷', badge: '', plate: '#402030' },
  { id: 'xiaochong', term: '小蟲', isDeer: false, emoji: '🐛', badge: '', plate: '#2a3810' },
  { id: 'jia', term: '家', isDeer: false, emoji: '🏠', badge: '', plate: '#1a3050' },
  { id: 'jie', term: '街', isDeer: false, emoji: '🏘️', badge: '', plate: '#2a3548' },
  { id: 'zaochen', term: '早晨', isDeer: false, emoji: '👋🌅', emojiDuo: true, badge: '', plate: '#3a3410' },
  { id: 'wanan', term: '晚安', isDeer: false, emoji: '🌙😴', emojiDuo: true, badge: '', plate: '#1a2a4a' },
];

/** 主題：先學再開考 */
const TOPICS = [
  {
    id: 'red_series',
    title: '紅輯',
    blurb: '對齊《我自己會讀》紅輯：讀完書考吓佢',
    cover: '📕',
    wordIds: [
      'wo', 'ni', 'ta_he', 'ta_she', 'women', 'nimen', 'tamen', 'baba', 'mama', 'yeye', 'maamaa', 'popo', 'gonggong', 'gege', 'jiejie', 'didi', 'meimei', 'baobao', 'pengyou', 'tongxue', 'laoshi_job', 'dajia', 'ziji', 'kanjian', 'tingjian', 'shuo', 'du', 'xie', 'hua_draw', 'chang_sing', 'lai', 'qu', 'hui', 'chu', 'ru', 'zuo_sit', 'zhan', 'zou', 'pao', 'tiao', 'fei', 'you_swim', 'pa', 'chi_eat', 'he_drink', 'shui_sleep', 'xing', 'xi', 'chuan_wear', 'tuo', 'kai', 'guan', 'na_take', 'fang', 'zhao', 'gei', 'wan_play', 'xiao_laugh', 'ku', 'bao_hug', 'xiang_think', 'yao_want', 'da_big', 'xiao_small', 'duo', 'shao', 'hao', 'huai', 'gao_tall', 'ai_short_height', 'chang_long', 'duan_short', 'kuai', 'man', 'xin_new', 'jiu_old', 'xiang_scent', 'tian', 're_hot', 'leng_cold', 'kaixin', 'guai', 'piaoliang', 'de', 'le', 'ma_q', 'ne', 'he_and', 'dou', 'ye_also', 'you_again', 'zai_again', 'hen', 'shi_be', 'bu', 'meiyou', 'you_have', 'zai', 'hui_can', 'keyi', 'zhe', 'na_that', 'na_which', 'shenme', 'weishenme', 'zenme', 'zheli', 'nali', 'nali_where', 'ge_mw', 'zhi_mw', 'ba_mw', 'yi', 'er', 'san', 'si', 'wu', 'liu', 'qi', 'ba', 'jiu', 'shi', 'jintian', 'zuotian', 'mingtian', 'zaoshang', 'xiawu', 'wanshang', 'xianzai', 'nian', 'yue_month', 'ri_day', 'xingqi', 'shengri', 'tiankong', 'ri', 'yue', 'xingxing', 'yun', 'yu_rain', 'feng', 'xue', 'shan_mountain', 'shui', 'huo', 'shu_tree', 'hua', 'cao', 'tou', 'lian', 'yan', 'erduo', 'bi', 'kou', 'yachi', 'shou', 'jiao', 'shouzhi', 'toufa', 'xin', 'shu', 'bi_pen', 'zhi_paper', 'shubao', 'wanju', 'qiu_ball', 'gongzai', 'yifu', 'kuzi', 'xiezi', 'wazi', 'maozi', 'men', 'chuanghu', 'chuangpu', 'yizi', 'deng', 'beizi_cup', 'fan', 'miantiao', 'bao', 'jidan', 'nai', 'guozhi', 'tangguo', 'binggan', 'dangao', 'xiaogou', 'xiaomao', 'xiaoyu', 'xiaoniao', 'tu', 'xiaoji', 'xiaoya', 'xiaoma', 'xiaoniu', 'xiaoyang', 'xiaozhu', 'xiaochong', 'jia', 'xuexiao', 'gongyuan', 'jie', 'shangchang', 'che', 'chuan', 'feiji', 'xiexie', 'shuijiao', 'ai_love', 'zaochen', 'wanan',
    ],
  },
  {
    id: 'numbers',
    title: '數字',
    blurb: '一到十，卡卡已經識！',
    cover: '🔢',
    wordIds: ['yi', 'er', 'san', 'si', 'wu', 'liu', 'qi', 'ba', 'jiu', 'shi'],
  },
  {
    id: 'colors',
    title: '顏色',
    blurb: '紅色黃色藍色綠色白色黑色紫色粉紅橙色咖啡色',
    cover: '🎨',
    wordIds: ['hong', 'huang', 'lan', 'lv', 'bai', 'hei', 'zi', 'fenhong', 'chengse', 'kafeise'],
  },
  {
    id: 'opposites',
    title: '相反位置',
    blurb: '大細多少、長短高矮、上下前後左右、裏面外面',
    cover: '↕️',
    wordIds: [
      'da_big', 'xiao_small', 'duo', 'shao',
      'chang_long', 'duan_short', 'gao_tall', 'ai_short_height',
      'shang', 'xia', 'qian_front', 'hou_back', 'zuo_left', 'you_right',
      'limian', 'waimian',
    ],
  },
  {
    id: 'weather',
    title: '天氣',
    blurb: '太陽、月亮、雲朵、下雨、雪花、大風、閃電、彩虹',
    cover: '☀️',
    wordIds: ['ri', 'yue', 'yun', 'yu_rain', 'xue', 'feng', 'dian', 'caihong'],
  },
  {
    id: 'nature',
    title: '自然',
    blurb: '星星、天空、花、草、樹、海、沙、火、葉',
    cover: '🌿',
    wordIds: ['xingxing', 'tiankong', 'hua', 'cao', 'shu_tree', 'hai', 'sha', 'huo', 'ye'],
  },
  {
    id: 'transport',
    title: '交通',
    blurb: '汽車、巴士、地鐵、的士、消防車…',
    cover: '🚗',
    wordIds: [
      'che', 'bashi', 'huoche', 'feiji', 'chuan', 'danche',
      'dishi', 'dianche', 'ditie', 'motuoche', 'xiaofangche', 'jiuhuche', 'jingche',
    ],
  },
  {
    id: 'body',
    title: '身體',
    blurb: '眼睛耳朵鼻子嘴巴手腳頭心',
    cover: '👀',
    wordIds: ['yan', 'erduo', 'bi', 'kou', 'shou', 'jiao', 'tou', 'xin'],
  },
  {
    id: 'emotions',
    title: '情緒',
    blurb: '開心、不開心、生氣、害怕、驚喜、害羞',
    cover: '😊',
    wordIds: ['kaixin', 'bukaixin', 'shengqi', 'haipa', 'jingxi', 'haixiu'],
  },
  {
    id: 'senses',
    title: '身體感覺',
    blurb: '累、餓、飽、渴、痛、熱、冷、香、臭',
    cover: '🥵',
    wordIds: ['lei', 'e_hungry', 'bao_full', 'ke_thirsty', 'tong', 're_hot', 'leng_cold', 'xiang_scent', 'chou'],
  },
  {
    id: 'family',
    title: '家庭',
    blurb: '爸爸媽媽爺爺婆婆哥哥姐姐弟弟妹妹寶寶',
    cover: '👨',
    wordIds: ['baba', 'mama', 'yeye', 'popo', 'gege', 'jiejie', 'didi', 'meimei', 'baobao'],
  },
  {
    id: 'food',
    title: '食物',
    blurb: '白飯、小食、肉類、海鮮同飲品',
    cover: '🍚',
    wordIds: [
      'fan', 'mian', 'bao', 'dan', 'nai', 'dangao',
      'shui', 'guozhi', 'xuegao', 'binggan', 'tangguo',
      'sanwenzi', 'hanbao', 'pisa', 'shutiao',
      'jirou', 'niurou', 'zhurou', 'yangrou', 'feiniu',
      'xia_shrimp', 'xie_crab', 'haixian',
    ],
  },
  {
    id: 'school',
    title: '學校用品',
    blurb: '書本、鉛筆、間尺、書包、足球、積木',
    cover: '📚',
    wordIds: ['shu', 'gangbi', 'chi', 'shubao', 'qiu', 'jimu'],
  },
  {
    id: 'places',
    title: '地方',
    blurb: '屋企、學校、醫院、超市、泳池、沙田…',
    cover: '🏠',
    wordIds: [
      'wuzi', 'xuexiao', 'keshi', 'gongyuan', 'youlechang', 'shangchang', 'chaoshi', 'jieshi',
      'tushuguan', 'tingchechang', 'shatian',
      'yiyuan', 'xiaofangju', 'jingchaju', 'jichang', 'haitan', 'canting', 'cesuo', 'yongchi',
    ],
  },
  {
    id: 'home',
    title: '屋企',
    blurb: '房間、傢俬、電器同家居設施',
    cover: '🛋️',
    wordIds: [
      'chufang', 'shuifang', 'yushi', 'yangtai',
      'chuangpu', 'zhentou', 'beizi', 'yizi', 'zhuozi', 'shafa', 'yigui', 'chouti',
      'dianshi', 'xuegui', 'xiyiji', 'fengshan', 'lengqi', 'dianhua', 'shizhong', 'deng',
      'men', 'mensuo', 'chuanghu', 'lajitong', 'xiangkuang', 'ditan',
      'xishoutai', 'shuilongtou', 'tuoxie',
    ],
  },
  {
    id: 'daily',
    title: '日常用品',
    blurb: '盥洗、餐具同隨身小物',
    cover: '🪥',
    wordIds: [
      'maojin', 'yashua', 'yagao', 'jing', 'shuzi', 'lifa', 'xitoushui', 'muyulu',
      'kouzhao', 'yanjing', 'shuihu', 'zhijin',
      'beizi_cup', 'wan', 'tangchi', 'kuaizi', 'chazi', 'panzi',
    ],
  },
  {
    id: 'zoo',
    title: '動物園',
    blurb: '鹿家族、猛獸同更多動物園朋友',
    cover: '🦁',
    wordIds: [
      'lu', 'meihualu', 'xunlu', 'tuolu', 'malu',
      'xiong', 'shizi', 'laohu', 'daxiang', 'hou',
      'xiongmao', 'changjinglu', 'banma', 'qie', 'hema', 'xiniu',
      'luotuo', 'daishu', 'shuxiong', 'huli', 'eyu', 'she', 'maotouying', 'lang',
      'haitun', 'haibao', 'kongque', 'honghe',
    ],
  },
  {
    id: 'small_animals',
    title: '小動物',
    blurb: '寵物、農場同奇趣小動物',
    cover: '🐶',
    wordIds: [
      'gou', 'mao', 'yu', 'niao', 'tu',
      'yang', 'niu', 'ma', 'zhu', 'ji', 'ya',
      'wa', 'chong', 'long', 'bianfu', 'ciwei',
    ],
  },
  {
    id: 'fruit',
    title: '水果',
    blurb: '蘋果、芒果、菠蘿、奇異果、櫻桃…',
    cover: '🍎',
    wordIds: [
      'pingguo', 'xiangjiao', 'cheng', 'putao', 'xigua', 'caomei',
      'mangguo', 'boluo', 'tao', 'ningmeng', 'yingtao', 'qiyiguo',
    ],
  },
  {
    id: 'veg',
    title: '蔬菜',
    blurb: '番茄、薯仔、蘑菇、黃瓜、南瓜…',
    cover: '🥕',
    wordIds: [
      'fanqie', 'hongluobo', 'yumi', 'baicai', 'qiezi', 'qingjiao',
      'shuzai', 'yangcong', 'mogu', 'huanggua', 'wandou', 'nangua',
    ],
  },
  {
    id: 'hk_food',
    title: '港式美食',
    blurb: '茶餐廳、小菜同屋企常見味道',
    cover: '🍽️',
    wordIds: [
      'feiniu_wudong', 'gulourou', 'dabianlu', 'yezi', 'maileji', 'roujiang_yifen',
      'wonton_mian', 'changfen', 'siumai', 'yudan', 'naicha', 'boluoyou',
      'fanqie_chaodan', 'zheng_yu', 'zheng_shuidan',
    ],
  },
  {
    id: 'jobs',
    title: '職業',
    blurb: '醫生、機師、太空人、科學家、運動員…',
    cover: '👨‍⚕️',
    wordIds: ['yisheng', 'hushi', 'laoshi_job', 'xiaofangyuan', 'jingcha', 'chushi', 'siji', 'nongfu',
      'jishi', 'kongjie', 'taikongren', 'yayi', 'shouyi', 'kexuejia', 'huajia', 'yinyuejia',
      'yundongyuan', 'bashi_siji', 'jianzhu_gongren', 'faxingshi', 'huanbao_zhuren', 'yiliao_xiaoshou'],
  },
  {
    id: 'dino',
    title: '恐龍',
    blurb: '暴龍、三角龍、梁龍、劍龍、翼龍、副櫛龍、甲龍、速龍…',
    cover: '🦖',
    wordIds: ['konglong', 'baolong', 'sanjiaolong', 'lianglong', 'jianlong', 'yilong', 'konglongdan', 'fuzhilong', 'jialong', 'sulong'],
  },
  {
    id: 'clothes',
    title: '衣物',
    blurb: '衫、褲、裙、鞋、襪、帽、頸巾、手套',
    cover: '👕',
    wordIds: ['shan', 'fu', 'kwan', 'haai', 'mat', 'mou', 'waihgan', 'shoutao'],
  },
  {
    id: 'bugs',
    title: '昆蟲小生物',
    blurb: '蝴蝶、蜜蜂、螞蟻、甲蟲、蜘蛛、蝸牛、毛毛蟲、蜻蜓',
    cover: '🦋',
    wordIds: ['hudie', 'mifeng', 'mayi', 'jiachong', 'zhizhu', 'woniu', 'maomaochong', 'qingting'],
  },
  {
    id: 'ocean',
    title: '海洋動物',
    blurb: '鯊魚、鯨魚、八爪魚、水母、海龜、海星、小丑魚、魷魚',
    cover: '🦈',
    wordIds: ['shayu', 'jingyu', 'bazhaoyu', 'shuimu', 'haigui', 'haixing', 'xiaochouyu', 'youyu'],
  },
];

function getWordById(id) {
  return WORDS.find((w) => w.id === id);
}

function getTopicById(id) {
  return TOPICS.find((t) => t.id === id);
}

function wordsForTopic(topicId) {
  const topic = getTopicById(topicId);
  if (!topic) return [...WORDS];
  return topic.wordIds.map(getWordById).filter(Boolean);
}

/**
 * 相反位置：學習頁成對出現（左邊固定「大／多／長…」邊）
 * [leftId, rightId]
 */
const OPPOSITE_PAIRS = [
  ['da_big', 'xiao_small'],
  ['duo', 'shao'],
  ['chang_long', 'duan_short'],
  ['gao_tall', 'ai_short_height'],
  ['shang', 'xia'],
  ['qian_front', 'hou_back'],
  ['zuo_left', 'you_right'],
  ['limian', 'waimian'],
];

/** @returns {{ left: object, right: object }[]} */
function oppositePairWords(enabledIds = null) {
  const enabled = enabledIds && enabledIds.length ? new Set(enabledIds) : null;
  return OPPOSITE_PAIRS.map(([leftId, rightId]) => {
    const left = getWordById(leftId);
    const right = getWordById(rightId);
    if (!left || !right) return null;
    if (enabled && (!enabled.has(left.id) || !enabled.has(right.id))) return null;
    return { left, right };
  }).filter(Boolean);
}

/** 攞某個字嘅相反詞（無就 null） */
function getOppositeWord(wordId) {
  for (const [a, b] of OPPOSITE_PAIRS) {
    if (a === wordId) return getWordById(b) || null;
    if (b === wordId) return getWordById(a) || null;
  }
  return null;
}

/** 開發時檢查：唔好有重複 id（例如屋同五撞 wu） */
(function assertUniqueWordIds() {
  const seen = Object.create(null);
  WORDS.forEach((w) => {
    if (seen[w.id]) {
      console.error('Duplicate word id:', w.id, seen[w.id], 'vs', w.term);
    }
    seen[w.id] = w.term;
  });
})();

/** 產生卡片插圖 HTML（大粒系統 Emoji；有 photo 就用真實相） */
function wordIllustHtml(word) {
  const badgeIsEmoji = word.badge && /\p{Extended_Pictographic}/u.test(word.badge);
  const badge = word.badge
    ? `<span class="emoji-badge${badgeIsEmoji ? ' emoji-badge-icon' : ''}" aria-hidden="true">${word.badge}</span>`
    : '';
  if (word.photo) {
    return `<span class="emoji-plate" style="--plate:${word.plate || '#122848'}">
    <img class="word-photo" src="${word.photo}" alt="${word.term}" loading="lazy" />
    ${badge}
  </span>`;
  }
  const faceClass = word.emojiDuo ? 'emoji-face emoji-face-duo' : 'emoji-face';
  return `<span class="emoji-plate" style="--plate:${word.plate || '#122848'}">
    <span class="${faceClass}" aria-hidden="true">${word.emoji}</span>
    ${badge}
  </span>`;
}

window.KakaWords = {
  WORDS,
  DEER_IDS,
  TOPICS,
  OPPOSITE_PAIRS,
  getWordById,
  getTopicById,
  wordsForTopic,
  oppositePairWords,
  getOppositeWord,
  wordIllustHtml,
};
